### ISSUE TITLE
improve styling of cards in team page (name, role and email id)

### ISSUE THREAD

**Issue by ashith1101** [Velocity-IIITDWD/iridescence#13]
Make the email id clickable

**Comment by Mandy767** [comment]
Done

**Comment by ashith1101** [comment]
![image](https://github.com/Velocity-IIITDWD/iridescence/assets/111903817/74fa761e-0357-4a4e-8ee0-f328244ec727)

resolve this issue

**Comment by Mandy767** [comment]
issue resolved created PR merge it

**Comment by Mandy767** [comment]
![Screenshot (55)](https://github.com/Velocity-IIITDWD/iridescence/assets/92856810/5dd0ba87-b40b-48c2-87e5-2e95e75e0173)

**Comment by Mandy767** [comment]
![Uploading Screenshot (56).png…]()

**Comment by Mandy767** [comment]
![Screenshot (56)](https://github.com/Velocity-IIITDWD/iridescence/assets/92856810/af182031-ad00-4114-b5ba-2ebd709bbd90)
